### ISSUE TITLE
 Broke the access restrictions area and only showed plain text

### ISSUE THREAD

**Issue by amalkowski** [jcorel/moodle-availability_enrolmentmethod#1]
The plugin is not working with Moodle version 4.1. It broke the access restrictions area and only showed plain text.

**Comment by izendegi** [comment]
Hi there,

We've also detected this issue on Moodle 3.11 with the latest version of the plugin.

When it happens this is the message I get in the browser console:

```
Uncaught SyntaxError: unexpected token: identifier
yui_combo.php:11:11767
Uncaught TypeError: M.core_availability is undefined
    <anonymous> https://moodle.domain.edu/course/modedit.php?add=resource&type=&course=16718&section=0&return=0&sr=0:2939
    _notify https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    use https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    _notify https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    T https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    _finish https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:16
    _onSuccess https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:16
    p https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    onSuccess https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    _finish https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _next https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _progress https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:13
    h https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _insert https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    execute https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _next https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _load https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    js https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:12
    _insert https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    insert https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    _continue https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    insert https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:17
    _use https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    use https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    <anonymous> https://moodle.domain.edu/course/modedit.php?add=resource&type=&course=16718&section=0&return=0&sr=0:2939
    _notify https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:40
    notify https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:40
    _notify https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:39
    _procSubs https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:39
    fireSimple https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:39
    _fire https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:39
    fire https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:40
    _load https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:115
    o https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:115
    g https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:8
    <anonymous> https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:116
    <anonymous> https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:116
    _attach https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    _attach https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:8
    _use https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    use https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:9
    <anonymous> https://moodle.domain.edu/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:567
```

**Comment by jcorel** [comment]
Hello and thank you both for the report.

I am unable to reproduce the issue. Could you give me more information? Module? Combination of restirctions? Thank you.

**Comment by izendegi** [comment]
Hi @jcorel ,

The effects are that when we enable this plugin and then try to add a new activity or resource (for example a file or an assignment) to availability restriction area doesn't load correctly (it's shown as a plain text field), and as a side effect the file uploading area doesn't load either:

![irudia](https://user-images.githubusercontent.com/5556433/213446362-310b7e16-f010-49e1-a5e8-3c58b23b8ee3.png)

It happens to us both on Moodle 3.11.11 and Moodle 4.1.1 with the latest version of the plugin.

**Comment by jcorel** [comment]
Thank you, @izendegi .

Sorry, I can't reproduce the issue... Do you have other third-party availability plugins installed? What theme are you using?

**Comment by izendegi** [comment]
We have tested the plugin on clean (core) Moodle 3.11 and 4.1 and we can reproduce the issue, so it may be something related with the software below Moodle.

Our web server is based on PostgreSQL (12.13) and PHP 7.4.

**Comment by jcorel** [comment]
@izendegi Thank you again. I'm going to test with PostgreSQL (12.13) and PHP 7.4. @amalkowski Can you please provide information on what PHP and database infrastructure you are using?

**Comment by jcorel** [comment]
@izendegi I have tried with PostgreSQL (12.13) and PHP 7.4 and I can't reproduce the issue. Sorry. I don't know what else I can try. 

I found some comments about similar issues in the past that also seem to be related to the availability restriction, including an issue of Moodle Tracker that was closed because the error could not be reproduced.

https://moodle.org/mod/forum/discuss.php?d=259943
https://tracker.moodle.org/browse/MDL-69487

**Comment by HSTing** [comment]
Hi, I had the same issue with Moodle4.0. I re-generated the [moodle-availability_enrolmentmethod-form-min.js](https://github.com/jcorel/moodle-availability_enrolmentmethod/blob/2fd9e8f8d70e1d8854fa1fc0099ea568c0a1c4a9/yui/build/moodle-availability_enrolmentmethod-form/moodle-availability_enrolmentmethod-form-min.js) file using the [moodle-availability_enrolmentmethod-form.js](https://github.com/jcorel/moodle-availability_enrolmentmethod/blob/2fd9e8f8d70e1d8854fa1fc0099ea568c0a1c4a9/yui/build/moodle-availability_enrolmentmethod-form/moodle-availability_enrolmentmethod-form.js) file and solved the bug.

**Comment by izendegi** [comment]
Hi,

I've applied the changed proposed by @HSTing and it has fixed the issue

**Comment by jcorel** [comment]
Thank you, @HSTing !
